// <auto-generated />
namespace DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class cartandcartitemtableadded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(cartandcartitemtableadded));
        
        string IMigrationMetadata.Id
        {
            get { return "202509231028027_cart and cart item table added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
