// <auto-generated />
namespace DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class usersaddedtousertable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(usersaddedtousertable));
        
        string IMigrationMetadata.Id
        {
            get { return "202509221107174_users added to user table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
